/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import java.awt.Color;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author abood
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    public NewJFrame() {
        initComponents();
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userpass = new javax.swing.JPasswordField();
        entertosign = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        usertext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 140, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 100, 30));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("_________________________________________");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 320, 20));

        userpass.setBackground(new java.awt.Color(11, 57, 80));
        userpass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userpass.setForeground(new java.awt.Color(255, 255, 255));
        userpass.setBorder(null);
        getContentPane().add(userpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 250, -1));

        entertosign.setBackground(new java.awt.Color(255, 255, 255));
        entertosign.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        entertosign.setText("Enter to sign");
        entertosign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entertosignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entertosignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entertosignMouseExited(evt);
            }
        });
        getContentPane().add(entertosign, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 170, 30));

        signup.setBackground(new java.awt.Color(255, 153, 0));
        signup.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        signup.setForeground(new java.awt.Color(11, 57, 80));
        signup.setText("sign up");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("_________________________________________");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 320, 20));

        usertext.setBackground(new java.awt.Color(11, 57, 80));
        usertext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usertext.setForeground(new java.awt.Color(255, 255, 255));
        usertext.setBorder(null);
        usertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertextActionPerformed(evt);
            }
        });
        getContentPane().add(usertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 250, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backdround.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertextActionPerformed

    private void hover(JButton b1){
        b1.setBackground(new Color(172,76,61));
        b1.setForeground(new Color(225,225,255));
    }
    private void hoverreset(JButton b1){
        b1.setBackground(new Color(225,225,255));
        b1.setForeground(new Color(11,57,80));
    }
    private void entertosignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entertosignMouseEntered
        // TODO add your handling code here:
        hover(entertosign);
    }//GEN-LAST:event_entertosignMouseEntered

    private void entertosignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entertosignMouseExited
        // TODO add your handling code here:
        hoverreset(entertosign);
    }//GEN-LAST:event_entertosignMouseExited

    private void entertosignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entertosignMouseClicked
            String a=usertext.getText();
            String b=userpass.getText();
      
       if( a.contains("awwad")||a.contains("mohammed") && b.contains("123456") ){
           setVisible(false);
           app cc=new app();
           cc.setVisible(true);
       }else{
                      JOptionPane.showMessageDialog(null, "user name are not defined");
       }

      
    }//GEN-LAST:event_entertosignMouseClicked

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_signupActionPerformed

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        // TODO add your handling code here:
     
    
        
      setVisible(false);
      signup_jframe xx=new signup_jframe();
      xx.setVisible(true);
    }//GEN-LAST:event_signupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entertosign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton signup;
    private javax.swing.JLabel user;
    private javax.swing.JPasswordField userpass;
    private javax.swing.JTextField usertext;
    // End of variables declaration//GEN-END:variables
}
